
@base_url = http://localhost:8080/api/users

POST {{base_url}}/authenticate
Content-Type: application/json

{
    "username": "admin@dev-10.com",
    "password": "admin"
}

###

POST {{base_url}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJwZXJzb25hbC1zb2xhci1mYXJtIiwic3ViIjoiYWRtaW5AZGV2LTEwLmNvbSIsImF1dGhvcml0aWVzIjoiQURNSU4iLCJleHAiOjE2OTY5NjAxMDN9.N32y89ZnfJR0scJj0Ef7t-mvtuVQg9UeG_-bcmECpqo

{
    "username": "known-working-student-submission@gmail.com"
}

###

GET {{base_url}}
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJwZXJzb25hbC1zb2xhci1mYXJtIiwic3ViIjoiYWRtaW5AZGV2LTEwLmNvbSIsImF1dGhvcml0aWVzIjoiQURNSU4iLCJleHAiOjE2OTY5NjAxMDN9.N32y89ZnfJR0scJj0Ef7t-mvtuVQg9UeG_-bcmECpqo

###

PUT {{base_url}}/account_setup
Content-Type: application/json

{
    "firstName": "Test!",
    "lastName": "Applicant!",
    "password": "password",
    "accountSetupToken": "LkNAtaANzSKLFYcHIoDN"
}
