@base_url = http://localhost:8080/api/users
@applicant_token = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJwZXJzb25hbC1zb2xhci1mYXJtIiwic3ViIjoia25vd24td29ya2luZy1zdHVkZW50LXN1Ym1pc3Npb25AZ21haWwuY29tIiwiYXV0aG9yaXRpZXMiOiJBUFBMSUNBTlQiLCJleHAiOjE2OTc0ODA3NjV9.u8qij2NCZgrHzDfkLVNXIl1GI5GMR9ORVeHBw912bkE
@admin_token = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJhcHBsaWNhbnQtc3VibWlzc2lvbnMiLCJzdWIiOiJhZG1pbkBkZXYtMTAuY29tIiwiYXV0aG9yaXRpZXMiOiJBRE1JTiIsImV4cCI6MTY5NzU4MTk4OH0.7CuQ9bFgBVVbI6FCelvamyIO76-c-Hu3QX_POrINNRY

@account_setup_token = MEZngnJFdaAOmzcFPMrm

POST {{base_url}}/authenticate
Content-Type: application/json

{
    "username": "admin@dev-10.com",
    "password": "admin"
}

###

POST {{base_url}}
Content-Type: application/json
Authorization: Bearer {{admin_token}}

{
    "username": "known-working-student-submission@gmail.com"
}

###

GET {{base_url}}
Authorization: Bearer {{admin_token}}

###

PUT {{base_url}}/account_setup
Content-Type: application/json

{
    "firstName": "Test!",
    "lastName": "Applicant!",
    "password": "password",
    "accountSetupToken": "{{account_setup_token}}"
}

###

POST {{base_url}}/authenticate
Content-Type: application/json

{
    "username": "known-working-student-submission@gmail.com",
    "password": "password"
}
